version: "3.8"

services:
  postgres:
    image: postgres:15.1-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./data:/data/postgres
    environment:
      PGUSER: ecom
      POSTGRES_PASSWORD: 12345678
      PGDATABASE: eccomerce
